# Generated by Django 5.1.4 on 2025-09-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsrecord',
            options={'permissions': [('view_analytics_data', 'Can view analytics data'), ('export_analytics_data', 'Can export analytics data')]},
        ),
    ]
