# Generated by Django 5.1.4 on 2025-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_analyticsrecord_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsrecord",
            name="created_by",
            field=models.UUIDField(
                blank=True,
                help_text="User ID from Identity Service who created this record",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analyticsrecord",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when record was soft deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analyticsrecord",
            name="deleted_by",
            field=models.UUIDField(
                blank=True,
                help_text="User ID from Identity Service who deleted this record",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analyticsrecord",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Mark record as deleted without actually removing it",
            ),
        ),
        migrations.AddField(
            model_name="analyticsrecord",
            name="organization_id",
            field=models.UUIDField(
                blank=True,
                help_text="Organization ID from Identity Service for multi-tenant isolation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analyticsrecord",
            name="updated_by",
            field=models.UUIDField(
                blank=True,
                help_text="User ID from Identity Service who last updated this record",
                null=True,
            ),
        ),
    ]
