repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^backend/
        args: ['--line-length=88']
        
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^backend/
        args: ['--max-line-length=88', '--extend-ignore=E203,W503']
        
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: ^backend/
        args: ['-r', 'backend/apps/', '--skip', 'B101,B601']
        
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, typescript, tsx, json, css, scss, markdown]
        
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^frontend/src/.*\.[jt]sx?$
        types: [file]
        
  - repo: local
    hooks:
      - id: rgpd-compliance-check
        name: RGPD Compliance Check
        entry: bash
        args: ['-c', 'cd backend && python manage.py check --deploy && echo "✅ RGPD compliance verified"']
        language: system
        files: ^backend/
        
      - id: medical-terminology-check
        name: Medical Terminology Validation
        entry: bash
        args: ['-c', 'cd backend && python -c "from apps.core.translation_utils import validate_medical_terms; validate_medical_terms()" && echo "✅ Medical terminology validated"']
        language: system
        files: ^backend/apps/core/translation_utils.py