# Generated by Django 5.2.6 on 2025-09-13 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_hash", models.CharField(max_length=40, unique=True)),
                ("timestamp", models.DateTimeField()),
                ("author", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("files_changed", models.JSONField(default=list)),
                ("branch", models.CharField(max_length=100)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commits",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow_id", models.CharField(max_length=100)),
                ("workflow_name", models.CharField(max_length=200)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                ("steps", models.JSONField(default=list)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "agents_involved",
                    models.ManyToManyField(related_name="workflows", to="agents.agent"),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=100)),
                ("message", models.TextField()),
                ("context", models.JSONField(default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="log_entries",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "level"],
                        name="logs_logent_timesta_d175e3_idx",
                    ),
                    models.Index(
                        fields=["source", "-timestamp"],
                        name="logs_logent_source_59f69f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("operation", models.CharField(max_length=100)),
                ("duration", models.FloatField(help_text="Duration in seconds")),
                ("success", models.BooleanField(default=True)),
                ("cpu_usage", models.FloatField(blank=True, null=True)),
                ("memory_usage", models.FloatField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_logs",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-timestamp"],
                        name="logs_perfor_agent_i_9909f2_idx",
                    ),
                    models.Index(
                        fields=["operation", "-timestamp"],
                        name="logs_perfor_operati_af7918_idx",
                    ),
                ],
            },
        ),
    ]
