name: Workflow Intelligence Agent
description: Manages workflow automation, business rules, and process intelligence
workdir: services/workflow-intelligence-service
instructions_file: services/workflow-intelligence-service/CLAUDE.md
permissions:
  read:
  - services/workflow-intelligence-service/**
  - docs/**
  - CLAUDE.md
  - services/workflow-intelligence-service/CLAUDE.md
  write:
  - services/workflow-intelligence-service/**
  execute:
  - python
  - pip
  - pytest
tools:
- Bash
- Read
- Write
- Edit
- MultiEdit
- Grep
- Glob
restrictions:
- Cannot modify other services directly
- Must validate business rules
- Must maintain audit trails
- Follow instructions in services/workflow-intelligence-service/CLAUDE.md
environment:
  SERVICE_NAME: workflow-intelligence-service
  PORT: '8004'
aliases:
  run: python main.py
  test: pytest
