# Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'microservices-monitor'
    environment: 'development'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'

  # Identity Service
  - job_name: 'identity-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['identity-service:8001']
        labels:
          service: 'identity-service'
          port: '8001'

  # Communication Service
  - job_name: 'communication-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['communication-service:8002']
        labels:
          service: 'communication-service'
          port: '8002'

  # Content Service
  - job_name: 'content-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['content-service:8003']
        labels:
          service: 'content-service'
          port: '8003'

  # Workflow Intelligence Service
  - job_name: 'workflow-intelligence-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['workflow-intelligence-service:8005']
        labels:
          service: 'workflow-intelligence-service'
          port: '8005'

  # Kong API Gateway
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
        labels:
          service: 'kong-admin'
    metrics_path: '/metrics'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          
  # PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgresql'

  # Loki - for logs
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          service: 'loki'

  # Jaeger - for tracing
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          service: 'jaeger'