apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: medicalhub
  labels:
    app: backend
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: backend
    tier: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http