#!/bin/bash
# Launch script for Backend Django Agent
# Generated by Agent Configurator

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Launching Backend Django Agent${NC}"
echo -e "${YELLOW}Specializes in Django backend development, APIs, and database operations${NC}"
echo ""

# Set working directory
WORKDIR="backend"
cd "$(dirname "$0")/../../../$WORKDIR"

# Export environment variables
export DJANGO_SETTINGS_MODULE="config.settings.development"
export PYTHONPATH="${workdir}"

# Display agent information
echo "📁 Working Directory: $(pwd)"
echo "🔧 Available Tools: Bash, Read, Write, Edit, MultiEdit, Grep, Glob"
echo ""

# Display permissions
echo "📝 Permissions:"
echo "  Read: backend/**, docs/**, CLAUDE.md..."
echo "  Write: backend/**..."
echo "  Execute: python, pip, django-admin..."
echo ""

# Display restrictions
echo "⚠️  Restrictions:"
echo "  - Cannot modify frontend code"
echo "  - Cannot modify infrastructure without approval"
echo "  - Must follow Django best practices"

echo ""

# Display available aliases
echo "🔗 Available Aliases:"
echo "  migrate: python manage.py migrate"
echo "  test: python manage.py test"
echo "  shell: python manage.py shell"

echo ""
echo -e "${GREEN}✅ Agent is configured and ready!${NC}"
echo ""
echo "You can now start working with this specialized agent configuration."
echo "All operations will be scoped to the defined permissions and restrictions."
