"""Initial migration with workflow tables

Revision ID: 980db70ea2c6
Revises: 
Create Date: 2025-09-09 15:28:13.983754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980db70ea2c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('initial_state', sa.String(length=100), nullable=False),
    sa.Column('states', sa.JSON(), nullable=False),
    sa.Column('transitions', sa.JSON(), nullable=False),
    sa.Column('business_rules', sa.JSON(), nullable=True),
    sa.Column('auto_transitions', sa.JSON(), nullable=True),
    sa.Column('sla_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_category'), 'workflow_definitions', ['category'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_organization_id'), 'workflow_definitions', ['organization_id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('definition_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_state', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('assigned_group', sa.String(length=255), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('execution_metadata', sa.JSON(), nullable=True),
    sa.Column('progress_percentage', sa.String(length=5), nullable=False),
    sa.Column('estimated_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_count', sa.String(length=10), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_assigned_group'), 'workflow_instances', ['assigned_group'], unique=False)
    op.create_index('ix_workflow_instances_assigned_status', 'workflow_instances', ['assigned_to', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_assigned_to'), 'workflow_instances', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_workflow_instances_current_state'), 'workflow_instances', ['current_state'], unique=False)
    op.create_index(op.f('ix_workflow_instances_definition_id'), 'workflow_instances', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_due_date'), 'workflow_instances', ['due_date'], unique=False)
    op.create_index('ix_workflow_instances_due_date_status', 'workflow_instances', ['due_date', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_entity_id'), 'workflow_instances', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_entity_type'), 'workflow_instances', ['entity_type'], unique=False)
    op.create_index('ix_workflow_instances_org_state', 'workflow_instances', ['organization_id', 'current_state'], unique=False)
    op.create_index('ix_workflow_instances_org_status', 'workflow_instances', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_organization_id'), 'workflow_instances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_priority'), 'workflow_instances', ['priority'], unique=False)
    op.create_index(op.f('ix_workflow_instances_status'), 'workflow_instances', ['status'], unique=False)
    op.create_table('ai_insights',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.String(length=20), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('estimated_impact', sa.String(length=20), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('acknowledged_at', sa.String(length=50), nullable=True),
    sa.Column('user_rating', sa.String(length=5), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_actionable', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_category'), 'ai_insights', ['category'], unique=False)
    op.create_index('ix_ai_insights_created_score', 'ai_insights', ['created_at', 'confidence_score'], unique=False)
    op.create_index(op.f('ix_ai_insights_insight_type'), 'ai_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_ai_insights_instance_id'), 'ai_insights', ['instance_id'], unique=False)
    op.create_index('ix_ai_insights_instance_type', 'ai_insights', ['instance_id', 'insight_type'], unique=False)
    op.create_index('ix_ai_insights_org_category', 'ai_insights', ['organization_id', 'category'], unique=False)
    op.create_index(op.f('ix_ai_insights_organization_id'), 'ai_insights', ['organization_id'], unique=False)
    op.create_index('ix_ai_insights_status_priority', 'ai_insights', ['status', 'priority'], unique=False)
    op.create_table('workflow_history',
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=100), nullable=True),
    sa.Column('to_state', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('action_metadata', sa.JSON(), nullable=True),
    sa.Column('system_info', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.String(length=20), nullable=True),
    sa.Column('was_successful', sa.String(length=5), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('validation_results', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflow_history_instance_created', 'workflow_history', ['instance_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workflow_history_instance_id'), 'workflow_history', ['instance_id'], unique=False)
    op.create_index('ix_workflow_history_trigger_type', 'workflow_history', ['trigger_type', 'created_at'], unique=False)
    op.create_index('ix_workflow_history_triggered_by', 'workflow_history', ['triggered_by', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_history_triggered_by', table_name='workflow_history')
    op.drop_index('ix_workflow_history_trigger_type', table_name='workflow_history')
    op.drop_index(op.f('ix_workflow_history_instance_id'), table_name='workflow_history')
    op.drop_index('ix_workflow_history_instance_created', table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index('ix_ai_insights_status_priority', table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_organization_id'), table_name='ai_insights')
    op.drop_index('ix_ai_insights_org_category', table_name='ai_insights')
    op.drop_index('ix_ai_insights_instance_type', table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_instance_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_insight_type'), table_name='ai_insights')
    op.drop_index('ix_ai_insights_created_score', table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_category'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_workflow_instances_status'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_priority'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_organization_id'), table_name='workflow_instances')
    op.drop_index('ix_workflow_instances_org_status', table_name='workflow_instances')
    op.drop_index('ix_workflow_instances_org_state', table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_entity_type'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_entity_id'), table_name='workflow_instances')
    op.drop_index('ix_workflow_instances_due_date_status', table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_due_date'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_definition_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_current_state'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_assigned_to'), table_name='workflow_instances')
    op.drop_index('ix_workflow_instances_assigned_status', table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_assigned_group'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_workflow_definitions_organization_id'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_category'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
