version: 1.0.0
project: ReactDjango-Hub
description: Agent configuration system for specialized Claude assistants

# Standardized agent definitions with consistent naming
agents:
  # Core Development Agents
  ag-backend:
    enabled: true
    description: Django Backend - Core business logic, data models, REST APIs
    working_directory: backend/
    specialization: Django, REST API, Business Logic
    
  ag-frontend:
    enabled: true
    description: React Frontend - User interface, components, state management
    working_directory: frontend/
    specialization: React, TypeScript, UI/UX
    
  # Microservice Specialists
  ag-identity:
    enabled: true
    description: Identity Service - Authentication, users, MFA, RBAC
    working_directory: services/identity-service/
    specialization: FastAPI, Authentication, MFA
    
  ag-communication:
    enabled: true
    description: Communication Service - Notifications, messaging, real-time
    working_directory: services/communication-service/
    specialization: Messaging, Notifications, Email/SMS
    
  ag-content:
    enabled: true
    description: Content Service - Document management, file storage
    working_directory: services/content-service/
    specialization: Document Management, Search, File Processing
    
  ag-workflow:
    enabled: true
    description: Workflow Intelligence - Process automation, AI workflows
    working_directory: services/workflow-intelligence-service/
    specialization: Workflows, Automation, AI Integration
    
  # Cross-Service Coordination
  ag-coordinator:
    enabled: true
    description: Services Coordinator - API gateway, service mesh, integration
    working_directory: services/
    specialization: Microservices Architecture, API Gateway, Service Mesh
    
  # Quality & Security
  ag-reviewer:
    enabled: true
    description: Code Review - Code quality, PR reviews, best practices
    working_directory: ./
    specialization: Code Quality, Security, Best Practices
    
  ag-security:
    enabled: true
    description: Security & Compliance - Security audits, vulnerability scanning
    working_directory: ./
    specialization: Security Audits, Compliance, Penetration Testing
    
  # Operations & Infrastructure
  ag-infrastructure:
    enabled: true
    description: Infrastructure - Docker, Kubernetes, CI/CD, deployment
    working_directory: infrastructure/
    specialization: Docker, Kubernetes, CI/CD
    
  # Note: tech-lead and claude-code-optimization-expert are deprecated
  # These roles are now handled by ag-coordinator and built-in Claude Code features
global_settings:
  audit_logging: true
  compliance:
  - HIPAA
  - RGPD
  default_branch: main
  worktree_base: ../ReactDjango-Hub-worktrees
communication:
  protocol: file-based
  shared_directory: .claude/shared
  message_format: yaml
